PR: Add validation prehooks
spyder-ide/spyder-plugin-cookiecutter pull request #19
Opened 2017-01-19 22:01 UTC by rlaverde

Fixes: #16

2017-01-19 22:02 UTC, goanpeca requested changes

2017-01-19 22:02 UTC, goanpeca commented on hooks/pre_gen_project.py
> +assert project_name.startswith('spyder'), 'Project slug should start with "spyder".'
Lets use regex

2017-01-19 22:02 UTC, goanpeca commented on hooks/pre_gen_project.py
> +if hasattr(project_name, 'isidentifier'):
I dont understand this :-|

2017-01-19 22:04 UTC, goanpeca commented
@rlaverde no need to add labels to PRs

2017-01-20 21:52 UTC, rlaverde commented
@goanpeca merge?

2017-01-20 23:23 UTC, goanpeca requested changes

2017-01-20 23:23 UTC, goanpeca commented on hooks/pre_gen_project.py
> +PROJECT_REGEX = r'^spyder_[_a-zA-Z0-9]+$'
it should be all lowercase, so A-Z is not ok

2017-01-20 23:23 UTC, goanpeca commented on hooks/pre_gen_project.py
> +
We should also validate the name of the repo or plugin

it should be 

Spyder-Something

or spyder-something

2017-01-21 00:10 UTC, rlaverde commented
As discussed by chat I only add validation for plugin_name, and I'll open another PR to make other variables invisible.

2022-03-28 15:08 UTC, closed without merging