PR: Add basic requirements in the template.
spyder-ide/spyder-plugin-cookiecutter pull request #26
Opened 2017-03-03 13:19 UTC by rlaverde

2017-03-03 18:08 UTC, goanpeca requested changes

2017-03-03 18:08 UTC, goanpeca commented on {{ cookiecutter.repo_name }}/requirements.txt
> +spyder==3.1.3
Equal?

2017-03-03 18:15 UTC, rlaverde commented on {{ cookiecutter.repo_name }}/requirements.txt
> +spyder==3.1.3
yes, I's the latest stable version, and I want to update dependencies using pyup #27 so dependencies should be pinned

2017-03-03 20:45 UTC, goanpeca commented on {{ cookiecutter.repo_name }}/requirements.txt
> +spyder==3.1.3
But why not >=, I don't like exact pinning, thats a bad practice

2017-03-03 23:38 UTC, rlaverde commented on {{ cookiecutter.repo_name }}/requirements.txt
> +spyder==3.1.3
But dependencies will updated using pyup, and exact pinning avoid them to be automatically updated.

2017-03-04 16:27 UTC, rlaverde commented on {{ cookiecutter.repo_name }}/requirements.txt
> +spyder==3.1.3
I'll change this for >= and exclude template dependencies from pyup

2017-03-05 21:54 UTC, goanpeca approved these changes
maybe just 3.1 is good enough?

2017-04-03 14:10 UTC, merged