PR: Remove redundant variables
spyder-ide/spyder-plugin-cookiecutter pull request #7
Opened 2017-01-17 02:26 UTC by rlaverde

Remove `project_name` and `repo_name`, and use instead `plugin_name` modifications.

2017-01-17 02:48 UTC, goanpeca requested changes

2017-01-17 02:48 UTC, goanpeca commented on spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '-') }}/circle.yml
> +    - $CMD_LINT_CIOCHECK spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '_') }} -dt: # note the colon
there is an error there should be _ not -

2017-01-17 02:48 UTC, goanpeca commented on spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '-') }}/circle.yml
> +    - $CMD_TEST_PYTEST spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '_') }} --cov=spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '_') }}: # note the colon        parallel: true
same here

2017-01-17 15:14 UTC, rlaverde commented
I'm not sure if this is a good change, directory and file names become really long and ugly .___.

I'm closing this, I think that's not to much harm to be asked two more questions, that will be ok to leave with the default value. Maybe we should add a comment in the Readme instead.

2017-01-17 15:20 UTC, goanpeca commented
>I'm not sure if this is a good change, directory and file names become really long and ugl

I dont understand how this is a problem?

2017-01-17 15:46 UTC, rlaverde commented
I address your comments, anyway I dont like to have files named:

`spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '-') }}/spyder_{{ cookiecutter.plugin_name.lower().replace(' ', '_') }}}/widgets/{{ cookiecutter.plugin_name.lower().replace(' ', '') }}gui.py`

and when writing in the terminal with escaping will become:

`spyder-\{\{\ cookiecutter.plugin_name.lower\(\).replace\(\'\ \'\,\ \'-\'\)\ \}\}/spyder_\{\{\ cookiecutter.plugin_name.lower\(\).replace\(\'\ \'\,\ \'_\'\)\ \}\}/widgets/\{\{\ cookiecutter.plugin_name.lower\(\).replace\(\'\ \'\,\ \'\'\)\ \}\}gui.py`

I think this is so error prone :confused:

2017-01-17 16:00 UTC, goanpeca requested changes

2017-01-17 16:00 UTC, goanpeca commented on spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '-') }}/circle.yml
> +    - $CMD_LINT_CIOCHECK spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '-') }} -dt: # note the colon
This is wrong we are calling the module here

2017-01-17 16:00 UTC, goanpeca commented on spyder-{{ cookiecutter.plugin_name.lower().replace(' ', '-') }}/circle.yml
same here

2017-01-19 15:56 UTC, goanpeca approved these changes

2017-09-13 12:14 UTC, rlaverde commented
Closing, I don't like the approach of this PR, I think is better to continue asking for 3 variables.

Maybe this change upstream https://github.com/audreyr/cookiecutter/issues/364 will make this a lot easier

2017-09-13 12:14 UTC, closed without merging